name: Meredith assessment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman
        run: 
          npm install -g newman
          npm install -g newman-reporter-html

      - name: Run Postman collection and show result
        run: |
          echo "🚀 Start Postman tests..."

          set +e
          newman run collections/Rijksmuseum.postman_collection.json \
            --reporters cli,html \
            --reporter-html-export test-report.html
          exit_code=$?
          set -e

          if [ $exit_code -eq 0 ]; then
            echo "✅ PASSED: All Postman API tests passed."
          else
            echo "❌ FAILED: One or more Postman API tests failed."
            exit 1
          fi

      - name: Upload HTML report as artefact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Html-report
          path: test-report.html